[package]
name = "poietica-automation-runtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
poietica-automation = { path = "../automation" }
poietica-conversation = { path = "../conversation" }
poietica-ledger = { path = "../ledger" }
poietica-time = { path = "../time" }
futures.workspace = true
log.workspace = true
tokio.workspace = true
tokio-util.workspace = true

[dev-dependencies]
tempfile.workspace = true
uuid.workspace = true

[lints]
workspace = true
