[package]
name = "poietica-automation-runtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
uuid.workspace = true
thiserror.workspace = true
poietica-conversation-runtime = { path = "../conversation-runtime" }
poietica-kap-client = { path = "../kap-client" }
poietica-automation = { path = "../automation" }
poietica-conversation = { path = "../conversation" }
poietica-ledger = { path = "../ledger" }
poietica-time = { path = "../time" }
log.workspace = true
tokio.workspace = true
tokio-util.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
