/*
 * 这个包的唯一出口。
 *
 * agent/ 是会话端口与线上词汇（类型，无实现）。timeline/ 把官方 transcript 投影成
 * 可渲染的时间线，interjection/ 持有待插话消息的顺序：纯函数与纯状态机，没有
 * React，能在 Node 里直接单测。session/ 在它上面管线程、转录、可调项与能力表。
 * 各段是同一条管线的前后半，边界留在包内的目录上；整个包不认识 React ——
 * hooks 与 Context 归 @poietica/assistant 的 conversation/，这条边由架构检查守着。
 */

export type {
  AgentCapabilityPort,
  AgentMcpServer,
  AgentMcpStatus,
  AgentPromptHandle,
  AgentPromptRequest,
  AgentSessionPort,
  AgentSkill,
  AgentToolkit,
  ApprovalAnswer,
  ApprovalDecision,
  ApprovalScope,
  ChatStatus,
  KapSessionId,
  KapStopReason,
  KapToolCallId,
  OpenedThread,
  PermissionPosturePort,
  PromptAsset,
  PromptConfiguration,
  PromptSkill,
  QuestionAnswer,
  QuestionAnswerMethod,
  QuestionChoice,
  QuestionItem,
  QuestionOption,
  QuestionOutcome,
  QuestionResponse,
  RunStatus,
  SessionConfigChoice,
  SessionConfigControl,
  SessionConfigPort,
  SessionConfigPurpose,
  SessionConfigReport,
  SessionGoal,
  SessionGoalStatus,
  SessionLink,
  SessionUsage,
  SessionUsagePort,
  SessionUsageReport,
  ThreadHistory,
  ThreadPort,
  ThreadRecord,
  ThreadSnapshot,
  ToolCallContent,
  ToolCallLocation,
  ToolCallStatus,
  ToolCallUpdate,
  ToolKind,
  TranscriptAgentId,
  TranscriptCatchUp,
  TranscriptPage,
  TranscriptPort,
  TranscriptSignal,
  TranscriptTurnId,
  TurnMark,
} from './agent'
export type {
  AttachmentIntake,
  AttachmentUpload,
  ComposerAsset,
  ComposerAssetContext,
} from './composer/attachment'
export type { Interjection } from './interjection'
export { InterjectionOutbox } from './interjection'
export type {
  AgentControls,
  SessionControlsFailureReport,
  ThreadWorkspaceList,
  Transcript,
} from './session'
export {
  AgentCapabilityStore,
  describeFailure,
  groupByWorkspace,
  isProjectlessWorkspaceRoot,
  normalizeWorkspaceRoot,
  permissionControlOf,
  permissionPostureOf,
  permissionPosturesOf,
  projectVisibleModelChoices,
  SessionControlsStore,
  ThreadsStore,
  TranscriptStore,
  workspaceRootName,
} from './session'
export type {
  BackgroundTaskItem,
  BackgroundTaskStatus,
  CompactionState,
  CompactionTimelineItem,
  FeedRow,
  LinkTimelineItem,
  MessageImage,
  PendingInteractions,
  PermissionItem,
  PlanItem,
  Presentation,
  QuestionTimelineItem,
  TimelineState,
  TodoItem,
  TodoStatus,
  ToolCallTimelineItem,
  ToolGroupPlan,
  TurnSealPlan,
} from './timeline'
export {
  activeScope,
  appendLocalError,
  appendUserMessage,
  channelNameOf,
  confirmRunCancellation,
  createTimelineState,
  currentTodos,
  delegateKey,
  delegationOf,
  inflightPromptId,
  isDelegation,
  lastAtOrBefore,
  liveMemberOf,
  pendingInteractions,
  pendingPermission,
  pendingPermissionCount,
  pendingQuestion,
  projectTranscript,
  rejectRunCancellation,
  requestRunCancellation,
  selectIsBusy,
  selectPresentation,
} from './timeline'
