/*
 * GENERATED by refactor.mjs — do not edit by hand.
 *
 * Aliases are resolved against the export list of the installed
 * @mynaui/icons-react build, so an icon-library upgrade that renames or removes a
 * glyph fails the script instead of the runtime.
 */

export {
  ArrowUp as SubmitIcon,
  Check as CheckIcon,
  ChevronDown as ChevronDownIcon,
  DangerCircle as FailureIcon,
  Dots as MoreIcon,
  Edit as PencilIcon,
  File as FileIcon,
  Globe as GlobeIcon,
  Message as ThreadIcon,
  Microphone as MicIcon,
  Paperclip as AttachIcon,
  Pin as PinIcon,
  PinSolid as PinFilledIcon,
  Plus as PlusIcon,
  Search as SearchIcon,
  Send as AgentIcon,
  Sparkles as ModelIcon,
  Spinner as SpinnerIcon,
  Square as StopIcon,
  Tool as ToolIcon,
  X as CloseIcon,
} from '@mynaui/icons-react'

/*
 * 思考过程的字形不在图标库里：库中没有 lightbulb，所以它是设计系统里的一个
 * 本地字形（见 components/icons/local-glyphs.tsx 的说明）。别名层在这里，
 * 所以调用点一个字都不用改。
 */
export { LightbulbIcon as ThinkingIcon } from '@poietica/foundations-design-system'
