// Generated by features/ai/acp-native/tests/live_turn.rs. Do not edit.
//
// One real turn, recorded verbatim. If a frame here fails validation the
// validator is wrong, not the recording. Regenerate with:
//
//   cargo test -p poietica-ai-acp-native --test live_turn -- --ignored

export interface RecordedFrame {
  readonly runId: string
  readonly seq: number
  readonly kind: string
  readonly frame: unknown
}

export const recordedTurn: readonly RecordedFrame[] = [
  {
    runId: '019f9c27-f559-75a1-b35a-45cc1461eff1',
    seq: 1,
    kind: 'run_started',
    frame: {
      sessionId: 'session_96ac89e8-dcfa-4c52-8f80-0e0039b0fbd8',
      kind: 'run_started',
      seq: 1,
      at: 1785031293134,
    },
  },
  {
    runId: '019f9c27-f559-75a1-b35a-45cc1461eff1',
    seq: 2,
    kind: 'acp_update',
    frame: {
      notification: {
        sessionId: 'session_96ac89e8-dcfa-4c52-8f80-0e0039b0fbd8',
        update: {
          sessionUpdate: 'available_commands_update',
          availableCommands: [
            {
              name: 'compact',
              description: 'Compact the conversation context',
              input: {
                hint: '<optional custom summarization instructions>',
              },
            },
            {
              name: 'status',
              description: 'Show current session status',
            },
            {
              name: 'usage',
              description: 'Show session token usage',
            },
            {
              name: 'mcp',
              description: 'Show MCP server status',
            },
            {
              name: 'tasks',
              description: 'List background tasks',
            },
            {
              name: 'help',
              description: 'Show available ACP commands',
            },
            {
              name: 'check-kimi-code-docs',
              description:
                'Answer questions about the Kimi Code product using the official documentation — CLI usage, configuration, slash commands, features, membership and quota, API onboarding, third-party tool setup, and error codes. Use when the user asks how Kimi Code works, how to set something up, or what a Kimi Code error message means.',
            },
            {
              name: 'custom-theme',
              description:
                "Create or edit a kimi-code custom color theme — a JSON file under the resolved KIMI_CODE_HOME data directory that recolors the TUI. Use when the user wants their own theme, asks for a specific palette or mood, or wants to tweak an existing custom theme's colors.",
            },
            {
              name: 'import-from-cc-codex',
              description:
                'Import Claude Code and Codex instructions, skills, and MCP settings into Kimi Code.',
            },
            {
              name: 'mcp-config',
              description: 'Configure MCP servers and handle MCP OAuth login.',
            },
            {
              name: 'sub-skill',
              description:
                'Discover and reorganize the skill inventory into hierarchical sub-skill bundles. Use when the user asks to review, group, or consolidate skills into a parent bundle.',
            },
            {
              name: 'sub-skill.consolidate',
              description:
                'Apply an approved sub-skill grouping by moving user-specified skills into a parent bundle, with timestamped backups of every modified directory.',
            },
            {
              name: 'sub-skill.review',
              description:
                'Analyze the available skill set and recommend candidate groups that could be consolidated into sub-skill bundles. Read-only — proposes a plan, does not move files.',
            },
            {
              name: 'update-config',
              description:
                "Inspect or edit kimi-code's own config — `config.toml` (model, provider, permission, hooks) and `tui.toml` (theme, editor, notifications, auto-update). Use when the user asks what a setting does or wants to change one.",
            },
            {
              name: 'write-goal',
              description:
                'Help the user craft a well-specified `/goal` objective for goal mode — turn a rough intention into a completion contract with a clear finish line, proof, boundaries, and stop rule. Use when the user asks for help writing, refining, or improving a goal.',
            },
            {
              name: 'skill:emil-design-eng',
              description:
                "This skill encodes Emil Kowalski's philosophy on UI polish, component design, animation decisions, and the invisible details that make software feel great.",
            },
            {
              name: 'skill:find-skills',
              description:
                'Helps users discover and install agent skills when they ask questions like "how do I do X", "find a skill for X", "is there a skill that can...", or express interest in extending capabilities. This skill should be used when the user is looking for functionality that might exist as an installable skill.',
            },
            {
              name: 'skill:transitions-dev',
              description:
                'Production-ready CSS transitions for web apps. Use when implementing notification badges, dropdowns, modals, panel reveals, page transitions, card resizes, number pop-ins, text swaps, or icon swaps. Triggers on "add a transition", "animate the dropdown", "make the modal open smoothly", "swap icon", "page slide", "stagger animation", "open / close transition", "make it animate", "tween the size", "fade between", "smooth open", "smooth close".',
            },
          ],
        },
      },
      kind: 'acp_update',
      seq: 2,
      at: 1785031293152,
    },
  },
  {
    runId: '019f9c27-f559-75a1-b35a-45cc1461eff1',
    seq: 3,
    kind: 'acp_update',
    frame: {
      notification: {
        sessionId: 'session_96ac89e8-dcfa-4c52-8f80-0e0039b0fbd8',
        update: {
          sessionUpdate: 'agent_thought_chunk',
          content: {
            type: 'text',
            text: 'The',
          },
        },
      },
      kind: 'acp_update',
      seq: 3,
      at: 1785031298078,
    },
  },
  {
    runId: '019f9c27-f559-75a1-b35a-45cc1461eff1',
    seq: 4,
    kind: 'acp_update',
    frame: {
      notification: {
        sessionId: 'session_96ac89e8-dcfa-4c52-8f80-0e0039b0fbd8',
        update: {
          sessionUpdate: 'agent_thought_chunk',
          content: {
            type: 'text',
            text: ' user',
          },
        },
      },
      kind: 'acp_update',
      seq: 4,
      at: 1785031298078,
    },
  },
  {
    runId: '019f9c27-f559-75a1-b35a-45cc1461eff1',
    seq: 5,
    kind: 'acp_update',
    frame: {
      notification: {
        sessionId: 'session_96ac89e8-dcfa-4c52-8f80-0e0039b0fbd8',
        update: {
          sessionUpdate: 'agent_thought_chunk',
          content: {
            type: 'text',
            text: ' wants',
          },
        },
      },
      kind: 'acp_update',
      seq: 5,
      at: 1785031298085,
    },
  },
  {
    runId: '019f9c27-f559-75a1-b35a-45cc1461eff1',
    seq: 6,
    kind: 'acp_update',
    frame: {
      notification: {
        sessionId: 'session_96ac89e8-dcfa-4c52-8f80-0e0039b0fbd8',
        update: {
          sessionUpdate: 'agent_thought_chunk',
          content: {
            type: 'text',
            text: ' me',
          },
        },
      },
      kind: 'acp_update',
      seq: 6,
      at: 1785031298085,
    },
  },
  {
    runId: '019f9c27-f559-75a1-b35a-45cc1461eff1',
    seq: 7,
    kind: 'acp_update',
    frame: {
      notification: {
        sessionId: 'session_96ac89e8-dcfa-4c52-8f80-0e0039b0fbd8',
        update: {
          sessionUpdate: 'agent_thought_chunk',
          content: {
            type: 'text',
            text: ' to',
          },
        },
      },
      kind: 'acp_update',
      seq: 7,
      at: 1785031298085,
    },
  },
  {
    runId: '019f9c27-f559-75a1-b35a-45cc1461eff1',
    seq: 8,
    kind: 'acp_update',
    frame: {
      notification: {
        sessionId: 'session_96ac89e8-dcfa-4c52-8f80-0e0039b0fbd8',
        update: {
          sessionUpdate: 'agent_thought_chunk',
          content: {
            type: 'text',
            text: ' reply',
          },
        },
      },
      kind: 'acp_update',
      seq: 8,
      at: 1785031298085,
    },
  },
  {
    runId: '019f9c27-f559-75a1-b35a-45cc1461eff1',
    seq: 9,
    kind: 'acp_update',
    frame: {
      notification: {
        sessionId: 'session_96ac89e8-dcfa-4c52-8f80-0e0039b0fbd8',
        update: {
          sessionUpdate: 'agent_thought_chunk',
          content: {
            type: 'text',
            text: ' with',
          },
        },
      },
      kind: 'acp_update',
      seq: 9,
      at: 1785031298085,
    },
  },
  {
    runId: '019f9c27-f559-75a1-b35a-45cc1461eff1',
    seq: 10,
    kind: 'acp_update',
    frame: {
      notification: {
        sessionId: 'session_96ac89e8-dcfa-4c52-8f80-0e0039b0fbd8',
        update: {
          sessionUpdate: 'agent_thought_chunk',
          content: {
            type: 'text',
            text: ' a',
          },
        },
      },
      kind: 'acp_update',
      seq: 10,
      at: 1785031298085,
    },
  },
  {
    runId: '019f9c27-f559-75a1-b35a-45cc1461eff1',
    seq: 11,
    kind: 'acp_update',
    frame: {
      notification: {
        sessionId: 'session_96ac89e8-dcfa-4c52-8f80-0e0039b0fbd8',
        update: {
          sessionUpdate: 'agent_thought_chunk',
          content: {
            type: 'text',
            text: ' single',
          },
        },
      },
      kind: 'acp_update',
      seq: 11,
      at: 1785031298085,
    },
  },
  {
    runId: '019f9c27-f559-75a1-b35a-45cc1461eff1',
    seq: 12,
    kind: 'acp_update',
    frame: {
      notification: {
        sessionId: 'session_96ac89e8-dcfa-4c52-8f80-0e0039b0fbd8',
        update: {
          sessionUpdate: 'agent_thought_chunk',
          content: {
            type: 'text',
            text: ' word',
          },
        },
      },
      kind: 'acp_update',
      seq: 12,
      at: 1785031298473,
    },
  },
  {
    runId: '019f9c27-f559-75a1-b35a-45cc1461eff1',
    seq: 13,
    kind: 'acp_update',
    frame: {
      notification: {
        sessionId: 'session_96ac89e8-dcfa-4c52-8f80-0e0039b0fbd8',
        update: {
          sessionUpdate: 'agent_thought_chunk',
          content: {
            type: 'text',
            text: ':',
          },
        },
      },
      kind: 'acp_update',
      seq: 13,
      at: 1785031298473,
    },
  },
  {
    runId: '019f9c27-f559-75a1-b35a-45cc1461eff1',
    seq: 14,
    kind: 'acp_update',
    frame: {
      notification: {
        sessionId: 'session_96ac89e8-dcfa-4c52-8f80-0e0039b0fbd8',
        update: {
          sessionUpdate: 'agent_thought_chunk',
          content: {
            type: 'text',
            text: ' "',
          },
        },
      },
      kind: 'acp_update',
      seq: 14,
      at: 1785031298474,
    },
  },
  {
    runId: '019f9c27-f559-75a1-b35a-45cc1461eff1',
    seq: 15,
    kind: 'acp_update',
    frame: {
      notification: {
        sessionId: 'session_96ac89e8-dcfa-4c52-8f80-0e0039b0fbd8',
        update: {
          sessionUpdate: 'agent_thought_chunk',
          content: {
            type: 'text',
            text: 'ready',
          },
        },
      },
      kind: 'acp_update',
      seq: 15,
      at: 1785031298476,
    },
  },
  {
    runId: '019f9c27-f559-75a1-b35a-45cc1461eff1',
    seq: 16,
    kind: 'acp_update',
    frame: {
      notification: {
        sessionId: 'session_96ac89e8-dcfa-4c52-8f80-0e0039b0fbd8',
        update: {
          sessionUpdate: 'agent_thought_chunk',
          content: {
            type: 'text',
            text: '".',
          },
        },
      },
      kind: 'acp_update',
      seq: 16,
      at: 1785031298476,
    },
  },
  {
    runId: '019f9c27-f559-75a1-b35a-45cc1461eff1',
    seq: 17,
    kind: 'acp_update',
    frame: {
      notification: {
        sessionId: 'session_96ac89e8-dcfa-4c52-8f80-0e0039b0fbd8',
        update: {
          sessionUpdate: 'agent_thought_chunk',
          content: {
            type: 'text',
            text: ' They',
          },
        },
      },
      kind: 'acp_update',
      seq: 17,
      at: 1785031298477,
    },
  },
  {
    runId: '019f9c27-f559-75a1-b35a-45cc1461eff1',
    seq: 18,
    kind: 'acp_update',
    frame: {
      notification: {
        sessionId: 'session_96ac89e8-dcfa-4c52-8f80-0e0039b0fbd8',
        update: {
          sessionUpdate: 'agent_thought_chunk',
          content: {
            type: 'text',
            text: ' explicitly',
          },
        },
      },
      kind: 'acp_update',
      seq: 18,
      at: 1785031298477,
    },
  },
  {
    runId: '019f9c27-f559-75a1-b35a-45cc1461eff1',
    seq: 19,
    kind: 'acp_update',
    frame: {
      notification: {
        sessionId: 'session_96ac89e8-dcfa-4c52-8f80-0e0039b0fbd8',
        update: {
          sessionUpdate: 'agent_thought_chunk',
          content: {
            type: 'text',
            text: ' say',
          },
        },
      },
      kind: 'acp_update',
      seq: 19,
      at: 1785031298477,
    },
  },
  {
    runId: '019f9c27-f559-75a1-b35a-45cc1461eff1',
    seq: 20,
    kind: 'acp_update',
    frame: {
      notification: {
        sessionId: 'session_96ac89e8-dcfa-4c52-8f80-0e0039b0fbd8',
        update: {
          sessionUpdate: 'agent_thought_chunk',
          content: {
            type: 'text',
            text: ' not',
          },
        },
      },
      kind: 'acp_update',
      seq: 20,
      at: 1785031298477,
    },
  },
  {
    runId: '019f9c27-f559-75a1-b35a-45cc1461eff1',
    seq: 21,
    kind: 'acp_update',
    frame: {
      notification: {
        sessionId: 'session_96ac89e8-dcfa-4c52-8f80-0e0039b0fbd8',
        update: {
          sessionUpdate: 'agent_thought_chunk',
          content: {
            type: 'text',
            text: ' to',
          },
        },
      },
      kind: 'acp_update',
      seq: 21,
      at: 1785031298477,
    },
  },
  {
    runId: '019f9c27-f559-75a1-b35a-45cc1461eff1',
    seq: 22,
    kind: 'acp_update',
    frame: {
      notification: {
        sessionId: 'session_96ac89e8-dcfa-4c52-8f80-0e0039b0fbd8',
        update: {
          sessionUpdate: 'agent_thought_chunk',
          content: {
            type: 'text',
            text: ' use',
          },
        },
      },
      kind: 'acp_update',
      seq: 22,
      at: 1785031298756,
    },
  },
  {
    runId: '019f9c27-f559-75a1-b35a-45cc1461eff1',
    seq: 23,
    kind: 'acp_update',
    frame: {
      notification: {
        sessionId: 'session_96ac89e8-dcfa-4c52-8f80-0e0039b0fbd8',
        update: {
          sessionUpdate: 'agent_thought_chunk',
          content: {
            type: 'text',
            text: ' any',
          },
        },
      },
      kind: 'acp_update',
      seq: 23,
      at: 1785031298756,
    },
  },
  {
    runId: '019f9c27-f559-75a1-b35a-45cc1461eff1',
    seq: 24,
    kind: 'acp_update',
    frame: {
      notification: {
        sessionId: 'session_96ac89e8-dcfa-4c52-8f80-0e0039b0fbd8',
        update: {
          sessionUpdate: 'agent_thought_chunk',
          content: {
            type: 'text',
            text: ' tools',
          },
        },
      },
      kind: 'acp_update',
      seq: 24,
      at: 1785031298756,
    },
  },
  {
    runId: '019f9c27-f559-75a1-b35a-45cc1461eff1',
    seq: 25,
    kind: 'acp_update',
    frame: {
      notification: {
        sessionId: 'session_96ac89e8-dcfa-4c52-8f80-0e0039b0fbd8',
        update: {
          sessionUpdate: 'agent_thought_chunk',
          content: {
            type: 'text',
            text: '.',
          },
        },
      },
      kind: 'acp_update',
      seq: 25,
      at: 1785031298756,
    },
  },
  {
    runId: '019f9c27-f559-75a1-b35a-45cc1461eff1',
    seq: 26,
    kind: 'acp_update',
    frame: {
      notification: {
        sessionId: 'session_96ac89e8-dcfa-4c52-8f80-0e0039b0fbd8',
        update: {
          sessionUpdate: 'agent_thought_chunk',
          content: {
            type: 'text',
            text: ' This',
          },
        },
      },
      kind: 'acp_update',
      seq: 26,
      at: 1785031298756,
    },
  },
  {
    runId: '019f9c27-f559-75a1-b35a-45cc1461eff1',
    seq: 27,
    kind: 'acp_update',
    frame: {
      notification: {
        sessionId: 'session_96ac89e8-dcfa-4c52-8f80-0e0039b0fbd8',
        update: {
          sessionUpdate: 'agent_thought_chunk',
          content: {
            type: 'text',
            text: ' is',
          },
        },
      },
      kind: 'acp_update',
      seq: 27,
      at: 1785031298757,
    },
  },
  {
    runId: '019f9c27-f559-75a1-b35a-45cc1461eff1',
    seq: 28,
    kind: 'acp_update',
    frame: {
      notification: {
        sessionId: 'session_96ac89e8-dcfa-4c52-8f80-0e0039b0fbd8',
        update: {
          sessionUpdate: 'agent_thought_chunk',
          content: {
            type: 'text',
            text: ' a',
          },
        },
      },
      kind: 'acp_update',
      seq: 28,
      at: 1785031298757,
    },
  },
  {
    runId: '019f9c27-f559-75a1-b35a-45cc1461eff1',
    seq: 29,
    kind: 'acp_update',
    frame: {
      notification: {
        sessionId: 'session_96ac89e8-dcfa-4c52-8f80-0e0039b0fbd8',
        update: {
          sessionUpdate: 'agent_thought_chunk',
          content: {
            type: 'text',
            text: ' simple',
          },
        },
      },
      kind: 'acp_update',
      seq: 29,
      at: 1785031298757,
    },
  },
  {
    runId: '019f9c27-f559-75a1-b35a-45cc1461eff1',
    seq: 30,
    kind: 'acp_update',
    frame: {
      notification: {
        sessionId: 'session_96ac89e8-dcfa-4c52-8f80-0e0039b0fbd8',
        update: {
          sessionUpdate: 'agent_thought_chunk',
          content: {
            type: 'text',
            text: ' direct',
          },
        },
      },
      kind: 'acp_update',
      seq: 30,
      at: 1785031298757,
    },
  },
  {
    runId: '019f9c27-f559-75a1-b35a-45cc1461eff1',
    seq: 31,
    kind: 'acp_update',
    frame: {
      notification: {
        sessionId: 'session_96ac89e8-dcfa-4c52-8f80-0e0039b0fbd8',
        update: {
          sessionUpdate: 'agent_thought_chunk',
          content: {
            type: 'text',
            text: ' request',
          },
        },
      },
      kind: 'acp_update',
      seq: 31,
      at: 1785031298757,
    },
  },
  {
    runId: '019f9c27-f559-75a1-b35a-45cc1461eff1',
    seq: 32,
    kind: 'acp_update',
    frame: {
      notification: {
        sessionId: 'session_96ac89e8-dcfa-4c52-8f80-0e0039b0fbd8',
        update: {
          sessionUpdate: 'agent_thought_chunk',
          content: {
            type: 'text',
            text: '.',
          },
        },
      },
      kind: 'acp_update',
      seq: 32,
      at: 1785031298855,
    },
  },
  {
    runId: '019f9c27-f559-75a1-b35a-45cc1461eff1',
    seq: 33,
    kind: 'acp_update',
    frame: {
      notification: {
        sessionId: 'session_96ac89e8-dcfa-4c52-8f80-0e0039b0fbd8',
        update: {
          sessionUpdate: 'agent_thought_chunk',
          content: {
            type: 'text',
            text: '',
          },
        },
      },
      kind: 'acp_update',
      seq: 33,
      at: 1785031298856,
    },
  },
  {
    runId: '019f9c27-f559-75a1-b35a-45cc1461eff1',
    seq: 34,
    kind: 'acp_update',
    frame: {
      notification: {
        sessionId: 'session_96ac89e8-dcfa-4c52-8f80-0e0039b0fbd8',
        update: {
          sessionUpdate: 'agent_message_chunk',
          content: {
            type: 'text',
            text: 'ready',
          },
        },
      },
      kind: 'acp_update',
      seq: 34,
      at: 1785031298856,
    },
  },
  {
    runId: '019f9c27-f559-75a1-b35a-45cc1461eff1',
    seq: 35,
    kind: 'run_finished',
    frame: {
      stopReason: 'end_turn',
      kind: 'run_finished',
      seq: 35,
      at: 1785031298890,
    },
  },
]
