[package]
name = "poietica-automation"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false
license.workspace = true
repository.workspace = true

[dependencies]
chrono.workspace = true
chrono-tz.workspace = true
croner.workspace = true
thiserror.workspace = true
uuid.workspace = true
serde.workspace = true
specta.workspace = true
schemars.workspace = true
time.workspace = true

[lints]
workspace = true
