/*
 * Icon shim for the vendored AI Elements subtree.
 *
 * Upstream imports lucide-react. This repository has one icon library, so
 * every icon the vendored files use is re-exported from @mynaui/icons-react under
 * the name upstream expects. Generated by refactor.mjs and validated against
 * the installed package, so a missing icon fails the build script rather than
 * silently rendering the wrong glyph.
 */

export {
  Book as BookIcon,
  Sparkles as BrainIcon,
  CheckCircle as CheckCircleIcon,
  Check as CheckIcon,
  ChevronDown as ChevronDownIcon,
  ChevronLeft as ChevronLeftIcon,
  ChevronRight as ChevronRightIcon,
  ChevronUp as ChevronUpIcon,
  Circle as CircleIcon,
  ClockCircle as ClockIcon,
  Copy as CopyIcon,
  Search as SearchIcon,
  Wrench as WrenchIcon,
  XCircle as XCircleIcon,
} from '@mynaui/icons-react'
