/*
 * 包的公开面。逐个具名导出，不用 export *：对外承诺了什么，读这一份文件就够。
 */

export {
  type ContributionInput,
  type ResolvedAgent,
  type ResolvedCommand,
  type ResolvedContributions,
  type ResolvedMcpServer,
  type ResolvedPrompt,
  type ResolvedSkill,
  resolveContributions,
} from './contribution'
export {
  type ArchiveFetch,
  DEFAULT_BRANCH_UNPLANNABLE,
  type DirectoryFetch,
  type FetchPlanning,
  type PlannedFetch,
  type PluginFetchPlan,
  planFetch,
  type UnplannableFetch,
} from './fetch-plan'
export {
  type ArchiveSource,
  type CommitRef,
  type DefaultBranchRef,
  type DirectorySource,
  describeInstallSource,
  type GitHubRef,
  type GitHubSource,
  PLUGIN_TRUST_TIERS,
  type PluginInstallSource,
  type PluginTrustTier,
  parseInstallSource,
  type ReleaseTagRef,
  requiresInstallConfirmation,
  type TreeRef,
  UNLISTED_TRUST,
} from './install-source'
export { type InstalledPlugin, resolutionOrder } from './installation'
export {
  type AbsentPrompt,
  type AcceptedManifest,
  COMMAND_DESCRIPTION_LIMIT,
  commandDescription,
  decodePluginManifest,
  type FilePrompt,
  type InlinePrompt,
  type ManifestDecoding,
  MISSING_COMMAND_DESCRIPTION,
  PLUGIN_MANIFEST_FILENAMES,
  PLUGIN_PROMPT_BUDGET_BYTES,
  type PluginAgentDeclaration,
  type PluginCommandDeclaration,
  type PluginDiagnostic,
  type PluginDiagnosticCode,
  type PluginManifest,
  type PluginMcpServerDeclaration,
  type PluginSystemPrompt,
  type RejectedManifest,
  SESSION_PROMPT_BUDGET_BYTES,
  UNSUPPORTED_MANIFEST_FIELDS,
  utf8ByteLength,
} from './manifest'
export {
  type AbsentCatalog,
  beginFetch,
  type CatalogDecoding,
  completeFetch,
  type DecodedCatalog,
  decodeMarketplaceCatalog,
  type FailedCatalog,
  type FetchingCatalog,
  failFetch,
  latestCatalog,
  MARKETPLACE_ABSENT,
  MARKETPLACE_CATALOG_VERSION,
  type MarketplaceCatalog,
  type MarketplaceEntry,
  type MarketplaceOrigin,
  type MarketplaceState,
  parseMarketplaceOrigin,
  type ReadyCatalog,
  shouldFetchOnOpen,
  type UndecodableCatalog,
} from './marketplace'
export {
  createPluginStore,
  type IdleInstall,
  INSTALL_IDLE,
  type InstallFlow,
  type PluginStore,
  type PluginStoreOptions,
  type PluginsViewModel,
  type RefusedInstall,
  type StagedInstall,
  type StagingInstall,
} from './plugin-store'
export {
  type DecodedLedger,
  decodePluginLedger,
  encodePluginLedger,
  type LedgerDecoding,
  PLUGIN_LEDGER_VERSION,
  type PluginRecord,
  type UndecodableLedger,
} from './record'
export { PluginsSurface, type PluginsSurfaceProps } from './surface/plugins-surface'
