/** 文案目录。键由 crates/problem 的 code.rs 产出，成套性由 bun run test:architecture 校验。 */
export const PROBLEM_COPY: Readonly<Record<string, string>> = {
  'problem.agentRejected': 'agent 拒绝了这次调用',
  'problem.agentStartFailed': 'agent 没能启动',
  'problem.agentUnavailable': '连不上 agent，稍后再试',
  'problem.assetRejected': '资源处理失败',
  'problem.cancelled': '已取消',
  'problem.capabilityMissing': '需要的能力还没有配置',
  'problem.contractDecodeFailed': '数据格式无效',
  'problem.deliveryUnknown': '这一轮的结果还没确认',
  'problem.fileUnavailable': '文件操作失败',
  'problem.gitRejected': 'git 拒绝了这次操作',
  'problem.hostFailed': '应用操作失败',
  'problem.internal': '应用操作失败',
  'problem.ledgerAppendFailed': '本地库写入失败',
  'problem.ledgerCorrupted': '本地库已损坏',
  'problem.permissionDenied': '没有权限',
  'problem.pluginRejected': '插件操作失败',
  'problem.requestInvalid': '请求参数无效',
  'problem.resourceMissing': '请求的资源不存在',
  'problem.settingsUnavailable': '配置文件读写失败',
  'problem.turnRejected': '这一轮请求被拒绝',
  'problem.workspaceUnavailable': '工作区不可用',
}
