import { describe, expect, it } from 'vitest'
import { parseRunEvent } from '../acp-event-schema'
import { recordedTurn as spokenTurn } from './__fixtures__/live-turn.generated'

/**
 * The renderer's validator, against frames a real agent actually sent.
 *
 * Every other test of this schema feeds it frames written to satisfy it, which
 * proves only that the schema agrees with its author. The fixture here is a
 * recording of one real turn, generated by the native crate and committed
 * unedited:
 *
 * ```text
 * $env:POIETICA_ACP_COMMAND = "kimi.CMD acp"
 * $env:POIETICA_ACP_CAPTURE = "<absolute path to __fixtures__/live-turn.generated.ts>"
 * cargo test -p poietica-agent-runtime-native --test live_turn -- --ignored --nocapture
 * ```
 *
 * The capture path has to be absolute because cargo runs a test binary from its
 * own crate directory, not from the workspace root.
 *
 * A frame this validator rejects is a frame the timeline never sees, so a
 * rejection here is a feature that silently does not work, not a test detail.
 *
 * One recording is never enough, because it only proves the shapes the agent
 * happened to send. Two more are wanted: a turn that cannot be answered
 * without reading a file, which is where tool calls come from, and a turn
 * that asks permission. Each is added by capturing it with the command above,
 * committing the file, and appending one line to `recordings`.
 *
 * This suite named both of them before either was committed, so the package
 * could not be typechecked at all — twelve errors from two missing files, and
 * with them the whole workspace typecheck. A suite that does not compile is
 * not coverage waiting to arrive; it is a build that is red for a reason
 * unrelated to the code under test.
 */

const recordings = [{ name: 'a plain answer', frames: spokenTurn }] as const

describe.each(recordings)('a recorded turn: $name', ({ frames }) => {
  it('is not empty', () => {
    expect(frames.length).toBeGreaterThan(0)
  })

  it('is accepted frame by frame', () => {
    const rejected = frames
      .map((captured) => ({ captured, parsed: parseRunEvent(captured.frame) }))
      .filter((entry) => !entry.parsed.ok)
      .map((entry) =>
        [
          `seq ${entry.captured.seq} (${entry.captured.kind})`,
          entry.parsed.ok ? '' : entry.parsed.issue,
          JSON.stringify(entry.captured.frame),
        ].join('\n  '),
      )

    expect(rejected).toEqual([])
  })

  it('opens and closes the way a turn is supposed to', () => {
    const kinds = frames.map((captured) => captured.kind)

    expect(kinds.at(0)).toBe('run_started')
    expect(kinds.at(-1)).toBe('run_finished')
  })

  it('numbers its frames densely from one', () => {
    const sequence = frames.map((captured) => captured.seq)

    expect(sequence).toEqual(sequence.map((_value, index) => index + 1))
  })

  it('reports which kinds of update the agent actually sends', () => {
    const kinds = new Set(
      frames
        .map((captured) => captured.frame)
        .filter(
          (frame): frame is { notification: { update: { sessionUpdate: string } } } =>
            typeof frame === 'object' && frame !== null && 'notification' in frame,
        )
        .map((frame) => frame.notification.update.sessionUpdate),
    )

    // Not an assertion about the agent, which is free to send what it likes.
    // This is the inventory the timeline has to cover, kept visible.
    console.info('session update kinds in the recording:', [...kinds].sort().join(', '))

    expect(kinds.size).toBeGreaterThan(0)
  })
})
