-- 一条对话是在哪个工作目录里开的。
--
-- 列表的一级索引就是它：对着一个工作目录干活的客户端，主线索是「在哪个项目
-- 里」，不是「什么时候说的」。
--
-- 可空，而空有确定的含义：这一列存在之前写下的行都属于默认那一个工作区（见
-- packages/agent-session/src/thread-order.ts 的 DEFAULT_WORKSPACE_ID）。那时候
-- 运行期只有一个工作目录，它们本来就都在它里面 —— 所以不需要回填，也不需要
-- 一个兼容分支，存量对话读回来一行不差。
--
-- 存的是归一化之后的绝对路径。归一化只发生在渲染层那一处入口
-- （packages/core/src/workspace-root.ts 的 normalizeWorkspaceRoot），这一侧
-- 原样收下：同一件事判两遍，就会有一天两边不一样。
--
-- 不建索引。list_threads 不按这一列过滤（分组在渲染层做），一个不会被用到的
-- 索引只是每次写入都要付的代价。要用它的那天再加。
ALTER TABLE threads ADD COLUMN workspace_root TEXT;
