[package]
name = "poietica-ledger"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false
license.workspace = true
repository.workspace = true

[dependencies]
poietica-conversation = { path = "../conversation" }
poietica-time = { path = "../time" }
rusqlite.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[lints]
workspace = true
