[package]
name = "poietica-git-adapter-native"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
poietica-process-host = { path = "../process-host" }
poietica-review-native = { path = "../review" }

futures.workspace = true
notify.workspace = true
thiserror.workspace = true
tokio.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
