// Generated by agent/runtime/native/tests/live_turn.rs. Do not edit.
//
// One real turn, recorded verbatim. If a frame here fails validation the
// validator is wrong, not the recording. Regenerate with:
//
//   cargo test -p poietica-agent-runtime-native --test live_turn -- --ignored

export interface RecordedFrame {
  readonly runId: string
  readonly seq: number
  readonly kind: string
  readonly frame: unknown
}

export const recordedTurn: readonly RecordedFrame[] = [
  {
    "runId": "019f9c44-6b72-76c3-9064-76385f83a7af",
    "seq": 1,
    "kind": "run_started",
    "frame": {
      "sessionId": "session_4f26c3f8-36ae-40fe-a881-c81e7413dc03",
      "kind": "run_started",
      "seq": 1,
      "at": 1785033158490
    }
  },
  {
    "runId": "019f9c44-6b72-76c3-9064-76385f83a7af",
    "seq": 2,
    "kind": "acp_update",
    "frame": {
      "notification": {
        "sessionId": "session_4f26c3f8-36ae-40fe-a881-c81e7413dc03",
        "update": {
          "sessionUpdate": "available_commands_update",
          "availableCommands": [
            {
              "name": "compact",
              "description": "Compact the conversation context",
              "input": {
                "hint": "<optional custom summarization instructions>"
              }
            },
            {
              "name": "status",
              "description": "Show current session status"
            },
            {
              "name": "usage",
              "description": "Show session token usage"
            },
            {
              "name": "mcp",
              "description": "Show MCP server status"
            },
            {
              "name": "tasks",
              "description": "List background tasks"
            },
            {
              "name": "help",
              "description": "Show available ACP commands"
            },
            {
              "name": "check-kimi-code-docs",
              "description": "Answer questions about the Kimi Code product using the official documentation — CLI usage, configuration, slash commands, features, membership and quota, API onboarding, third-party tool setup, and error codes. Use when the user asks how Kimi Code works, how to set something up, or what a Kimi Code error message means."
            },
            {
              "name": "custom-theme",
              "description": "Create or edit a kimi-code custom color theme — a JSON file under the resolved KIMI_CODE_HOME data directory that recolors the TUI. Use when the user wants their own theme, asks for a specific palette or mood, or wants to tweak an existing custom theme's colors."
            },
            {
              "name": "import-from-cc-codex",
              "description": "Import Claude Code and Codex instructions, skills, and MCP settings into Kimi Code."
            },
            {
              "name": "mcp-config",
              "description": "Configure MCP servers and handle MCP OAuth login."
            },
            {
              "name": "sub-skill",
              "description": "Discover and reorganize the skill inventory into hierarchical sub-skill bundles. Use when the user asks to review, group, or consolidate skills into a parent bundle."
            },
            {
              "name": "sub-skill.consolidate",
              "description": "Apply an approved sub-skill grouping by moving user-specified skills into a parent bundle, with timestamped backups of every modified directory."
            },
            {
              "name": "sub-skill.review",
              "description": "Analyze the available skill set and recommend candidate groups that could be consolidated into sub-skill bundles. Read-only — proposes a plan, does not move files."
            },
            {
              "name": "update-config",
              "description": "Inspect or edit kimi-code's own config — `config.toml` (model, provider, permission, hooks) and `tui.toml` (theme, editor, notifications, auto-update). Use when the user asks what a setting does or wants to change one."
            },
            {
              "name": "write-goal",
              "description": "Help the user craft a well-specified `/goal` objective for goal mode — turn a rough intention into a completion contract with a clear finish line, proof, boundaries, and stop rule. Use when the user asks for help writing, refining, or improving a goal."
            },
            {
              "name": "skill:emil-design-eng",
              "description": "This skill encodes Emil Kowalski's philosophy on UI polish, component design, animation decisions, and the invisible details that make software feel great."
            },
            {
              "name": "skill:find-skills",
              "description": "Helps users discover and install agent skills when they ask questions like \"how do I do X\", \"find a skill for X\", \"is there a skill that can...\", or express interest in extending capabilities. This skill should be used when the user is looking for functionality that might exist as an installable skill."
            },
            {
              "name": "skill:transitions-dev",
              "description": "Production-ready CSS transitions for web apps. Use when implementing notification badges, dropdowns, modals, panel reveals, page transitions, card resizes, number pop-ins, text swaps, or icon swaps. Triggers on \"add a transition\", \"animate the dropdown\", \"make the modal open smoothly\", \"swap icon\", \"page slide\", \"stagger animation\", \"open / close transition\", \"make it animate\", \"tween the size\", \"fade between\", \"smooth open\", \"smooth close\"."
            }
          ]
        }
      },
      "kind": "acp_update",
      "seq": 2,
      "at": 1785033158510
    }
  },
  {
    "runId": "019f9c44-6b72-76c3-9064-76385f83a7af",
    "seq": 3,
    "kind": "acp_update",
    "frame": {
      "notification": {
        "sessionId": "session_4f26c3f8-36ae-40fe-a881-c81e7413dc03",
        "update": {
          "sessionUpdate": "agent_thought_chunk",
          "content": {
            "type": "text",
            "text": "The"
          }
        }
      },
      "kind": "acp_update",
      "seq": 3,
      "at": 1785033161876
    }
  },
  {
    "runId": "019f9c44-6b72-76c3-9064-76385f83a7af",
    "seq": 4,
    "kind": "acp_update",
    "frame": {
      "notification": {
        "sessionId": "session_4f26c3f8-36ae-40fe-a881-c81e7413dc03",
        "update": {
          "sessionUpdate": "agent_thought_chunk",
          "content": {
            "type": "text",
            "text": " user"
          }
        }
      },
      "kind": "acp_update",
      "seq": 4,
      "at": 1785033161876
    }
  },
  {
    "runId": "019f9c44-6b72-76c3-9064-76385f83a7af",
    "seq": 5,
    "kind": "acp_update",
    "frame": {
      "notification": {
        "sessionId": "session_4f26c3f8-36ae-40fe-a881-c81e7413dc03",
        "update": {
          "sessionUpdate": "agent_thought_chunk",
          "content": {
            "type": "text",
            "text": " wants"
          }
        }
      },
      "kind": "acp_update",
      "seq": 5,
      "at": 1785033161876
    }
  },
  {
    "runId": "019f9c44-6b72-76c3-9064-76385f83a7af",
    "seq": 6,
    "kind": "acp_update",
    "frame": {
      "notification": {
        "sessionId": "session_4f26c3f8-36ae-40fe-a881-c81e7413dc03",
        "update": {
          "sessionUpdate": "agent_thought_chunk",
          "content": {
            "type": "text",
            "text": " me"
          }
        }
      },
      "kind": "acp_update",
      "seq": 6,
      "at": 1785033161880
    }
  },
  {
    "runId": "019f9c44-6b72-76c3-9064-76385f83a7af",
    "seq": 7,
    "kind": "acp_update",
    "frame": {
      "notification": {
        "sessionId": "session_4f26c3f8-36ae-40fe-a881-c81e7413dc03",
        "update": {
          "sessionUpdate": "agent_thought_chunk",
          "content": {
            "type": "text",
            "text": " to"
          }
        }
      },
      "kind": "acp_update",
      "seq": 7,
      "at": 1785033161881
    }
  },
  {
    "runId": "019f9c44-6b72-76c3-9064-76385f83a7af",
    "seq": 8,
    "kind": "acp_update",
    "frame": {
      "notification": {
        "sessionId": "session_4f26c3f8-36ae-40fe-a881-c81e7413dc03",
        "update": {
          "sessionUpdate": "agent_thought_chunk",
          "content": {
            "type": "text",
            "text": " create"
          }
        }
      },
      "kind": "acp_update",
      "seq": 8,
      "at": 1785033161881
    }
  },
  {
    "runId": "019f9c44-6b72-76c3-9064-76385f83a7af",
    "seq": 9,
    "kind": "acp_update",
    "frame": {
      "notification": {
        "sessionId": "session_4f26c3f8-36ae-40fe-a881-c81e7413dc03",
        "update": {
          "sessionUpdate": "agent_thought_chunk",
          "content": {
            "type": "text",
            "text": " a"
          }
        }
      },
      "kind": "acp_update",
      "seq": 9,
      "at": 1785033161881
    }
  },
  {
    "runId": "019f9c44-6b72-76c3-9064-76385f83a7af",
    "seq": 10,
    "kind": "acp_update",
    "frame": {
      "notification": {
        "sessionId": "session_4f26c3f8-36ae-40fe-a881-c81e7413dc03",
        "update": {
          "sessionUpdate": "agent_thought_chunk",
          "content": {
            "type": "text",
            "text": " file"
          }
        }
      },
      "kind": "acp_update",
      "seq": 10,
      "at": 1785033161881
    }
  },
  {
    "runId": "019f9c44-6b72-76c3-9064-76385f83a7af",
    "seq": 11,
    "kind": "acp_update",
    "frame": {
      "notification": {
        "sessionId": "session_4f26c3f8-36ae-40fe-a881-c81e7413dc03",
        "update": {
          "sessionUpdate": "agent_thought_chunk",
          "content": {
            "type": "text",
            "text": " named"
          }
        }
      },
      "kind": "acp_update",
      "seq": 11,
      "at": 1785033161881
    }
  },
  {
    "runId": "019f9c44-6b72-76c3-9064-76385f83a7af",
    "seq": 12,
    "kind": "acp_update",
    "frame": {
      "notification": {
        "sessionId": "session_4f26c3f8-36ae-40fe-a881-c81e7413dc03",
        "update": {
          "sessionUpdate": "agent_thought_chunk",
          "content": {
            "type": "text",
            "text": " `"
          }
        }
      },
      "kind": "acp_update",
      "seq": 12,
      "at": 1785033162093
    }
  },
  {
    "runId": "019f9c44-6b72-76c3-9064-76385f83a7af",
    "seq": 13,
    "kind": "acp_update",
    "frame": {
      "notification": {
        "sessionId": "session_4f26c3f8-36ae-40fe-a881-c81e7413dc03",
        "update": {
          "sessionUpdate": "agent_thought_chunk",
          "content": {
            "type": "text",
            "text": "probe"
          }
        }
      },
      "kind": "acp_update",
      "seq": 13,
      "at": 1785033162093
    }
  },
  {
    "runId": "019f9c44-6b72-76c3-9064-76385f83a7af",
    "seq": 14,
    "kind": "acp_update",
    "frame": {
      "notification": {
        "sessionId": "session_4f26c3f8-36ae-40fe-a881-c81e7413dc03",
        "update": {
          "sessionUpdate": "agent_thought_chunk",
          "content": {
            "type": "text",
            "text": ".txt"
          }
        }
      },
      "kind": "acp_update",
      "seq": 14,
      "at": 1785033162093
    }
  },
  {
    "runId": "019f9c44-6b72-76c3-9064-76385f83a7af",
    "seq": 15,
    "kind": "acp_update",
    "frame": {
      "notification": {
        "sessionId": "session_4f26c3f8-36ae-40fe-a881-c81e7413dc03",
        "update": {
          "sessionUpdate": "agent_thought_chunk",
          "content": {
            "type": "text",
            "text": "`"
          }
        }
      },
      "kind": "acp_update",
      "seq": 15,
      "at": 1785033162093
    }
  },
  {
    "runId": "019f9c44-6b72-76c3-9064-76385f83a7af",
    "seq": 16,
    "kind": "acp_update",
    "frame": {
      "notification": {
        "sessionId": "session_4f26c3f8-36ae-40fe-a881-c81e7413dc03",
        "update": {
          "sessionUpdate": "agent_thought_chunk",
          "content": {
            "type": "text",
            "text": " in"
          }
        }
      },
      "kind": "acp_update",
      "seq": 16,
      "at": 1785033162093
    }
  },
  {
    "runId": "019f9c44-6b72-76c3-9064-76385f83a7af",
    "seq": 17,
    "kind": "acp_update",
    "frame": {
      "notification": {
        "sessionId": "session_4f26c3f8-36ae-40fe-a881-c81e7413dc03",
        "update": {
          "sessionUpdate": "agent_thought_chunk",
          "content": {
            "type": "text",
            "text": " the"
          }
        }
      },
      "kind": "acp_update",
      "seq": 17,
      "at": 1785033162100
    }
  },
  {
    "runId": "019f9c44-6b72-76c3-9064-76385f83a7af",
    "seq": 18,
    "kind": "acp_update",
    "frame": {
      "notification": {
        "sessionId": "session_4f26c3f8-36ae-40fe-a881-c81e7413dc03",
        "update": {
          "sessionUpdate": "agent_thought_chunk",
          "content": {
            "type": "text",
            "text": " current"
          }
        }
      },
      "kind": "acp_update",
      "seq": 18,
      "at": 1785033162101
    }
  },
  {
    "runId": "019f9c44-6b72-76c3-9064-76385f83a7af",
    "seq": 19,
    "kind": "acp_update",
    "frame": {
      "notification": {
        "sessionId": "session_4f26c3f8-36ae-40fe-a881-c81e7413dc03",
        "update": {
          "sessionUpdate": "agent_thought_chunk",
          "content": {
            "type": "text",
            "text": " directory"
          }
        }
      },
      "kind": "acp_update",
      "seq": 19,
      "at": 1785033162101
    }
  },
  {
    "runId": "019f9c44-6b72-76c3-9064-76385f83a7af",
    "seq": 20,
    "kind": "acp_update",
    "frame": {
      "notification": {
        "sessionId": "session_4f26c3f8-36ae-40fe-a881-c81e7413dc03",
        "update": {
          "sessionUpdate": "agent_thought_chunk",
          "content": {
            "type": "text",
            "text": " with"
          }
        }
      },
      "kind": "acp_update",
      "seq": 20,
      "at": 1785033162101
    }
  },
  {
    "runId": "019f9c44-6b72-76c3-9064-76385f83a7af",
    "seq": 21,
    "kind": "acp_update",
    "frame": {
      "notification": {
        "sessionId": "session_4f26c3f8-36ae-40fe-a881-c81e7413dc03",
        "update": {
          "sessionUpdate": "agent_thought_chunk",
          "content": {
            "type": "text",
            "text": " the"
          }
        }
      },
      "kind": "acp_update",
      "seq": 21,
      "at": 1785033162101
    }
  },
  {
    "runId": "019f9c44-6b72-76c3-9064-76385f83a7af",
    "seq": 22,
    "kind": "acp_update",
    "frame": {
      "notification": {
        "sessionId": "session_4f26c3f8-36ae-40fe-a881-c81e7413dc03",
        "update": {
          "sessionUpdate": "agent_thought_chunk",
          "content": {
            "type": "text",
            "text": " single"
          }
        }
      },
      "kind": "acp_update",
      "seq": 22,
      "at": 1785033162371
    }
  },
  {
    "runId": "019f9c44-6b72-76c3-9064-76385f83a7af",
    "seq": 23,
    "kind": "acp_update",
    "frame": {
      "notification": {
        "sessionId": "session_4f26c3f8-36ae-40fe-a881-c81e7413dc03",
        "update": {
          "sessionUpdate": "agent_thought_chunk",
          "content": {
            "type": "text",
            "text": " word"
          }
        }
      },
      "kind": "acp_update",
      "seq": 23,
      "at": 1785033162372
    }
  },
  {
    "runId": "019f9c44-6b72-76c3-9064-76385f83a7af",
    "seq": 24,
    "kind": "acp_update",
    "frame": {
      "notification": {
        "sessionId": "session_4f26c3f8-36ae-40fe-a881-c81e7413dc03",
        "update": {
          "sessionUpdate": "agent_thought_chunk",
          "content": {
            "type": "text",
            "text": " \""
          }
        }
      },
      "kind": "acp_update",
      "seq": 24,
      "at": 1785033162372
    }
  },
  {
    "runId": "019f9c44-6b72-76c3-9064-76385f83a7af",
    "seq": 25,
    "kind": "acp_update",
    "frame": {
      "notification": {
        "sessionId": "session_4f26c3f8-36ae-40fe-a881-c81e7413dc03",
        "update": {
          "sessionUpdate": "agent_thought_chunk",
          "content": {
            "type": "text",
            "text": "probe"
          }
        }
      },
      "kind": "acp_update",
      "seq": 25,
      "at": 1785033162372
    }
  },
  {
    "runId": "019f9c44-6b72-76c3-9064-76385f83a7af",
    "seq": 26,
    "kind": "acp_update",
    "frame": {
      "notification": {
        "sessionId": "session_4f26c3f8-36ae-40fe-a881-c81e7413dc03",
        "update": {
          "sessionUpdate": "agent_thought_chunk",
          "content": {
            "type": "text",
            "text": "\"."
          }
        }
      },
      "kind": "acp_update",
      "seq": 26,
      "at": 1785033162372
    }
  },
  {
    "runId": "019f9c44-6b72-76c3-9064-76385f83a7af",
    "seq": 27,
    "kind": "acp_update",
    "frame": {
      "notification": {
        "sessionId": "session_4f26c3f8-36ae-40fe-a881-c81e7413dc03",
        "update": {
          "sessionUpdate": "agent_thought_chunk",
          "content": {
            "type": "text",
            "text": " This"
          }
        }
      },
      "kind": "acp_update",
      "seq": 27,
      "at": 1785033162372
    }
  },
  {
    "runId": "019f9c44-6b72-76c3-9064-76385f83a7af",
    "seq": 28,
    "kind": "acp_update",
    "frame": {
      "notification": {
        "sessionId": "session_4f26c3f8-36ae-40fe-a881-c81e7413dc03",
        "update": {
          "sessionUpdate": "agent_thought_chunk",
          "content": {
            "type": "text",
            "text": " is"
          }
        }
      },
      "kind": "acp_update",
      "seq": 28,
      "at": 1785033162372
    }
  },
  {
    "runId": "019f9c44-6b72-76c3-9064-76385f83a7af",
    "seq": 29,
    "kind": "acp_update",
    "frame": {
      "notification": {
        "sessionId": "session_4f26c3f8-36ae-40fe-a881-c81e7413dc03",
        "update": {
          "sessionUpdate": "agent_thought_chunk",
          "content": {
            "type": "text",
            "text": " a"
          }
        }
      },
      "kind": "acp_update",
      "seq": 29,
      "at": 1785033162372
    }
  },
  {
    "runId": "019f9c44-6b72-76c3-9064-76385f83a7af",
    "seq": 30,
    "kind": "acp_update",
    "frame": {
      "notification": {
        "sessionId": "session_4f26c3f8-36ae-40fe-a881-c81e7413dc03",
        "update": {
          "sessionUpdate": "agent_thought_chunk",
          "content": {
            "type": "text",
            "text": " straightforward"
          }
        }
      },
      "kind": "acp_update",
      "seq": 30,
      "at": 1785033162372
    }
  },
  {
    "runId": "019f9c44-6b72-76c3-9064-76385f83a7af",
    "seq": 31,
    "kind": "acp_update",
    "frame": {
      "notification": {
        "sessionId": "session_4f26c3f8-36ae-40fe-a881-c81e7413dc03",
        "update": {
          "sessionUpdate": "agent_thought_chunk",
          "content": {
            "type": "text",
            "text": " task"
          }
        }
      },
      "kind": "acp_update",
      "seq": 31,
      "at": 1785033162372
    }
  },
  {
    "runId": "019f9c44-6b72-76c3-9064-76385f83a7af",
    "seq": 32,
    "kind": "acp_update",
    "frame": {
      "notification": {
        "sessionId": "session_4f26c3f8-36ae-40fe-a881-c81e7413dc03",
        "update": {
          "sessionUpdate": "agent_thought_chunk",
          "content": {
            "type": "text",
            "text": ".\n\n"
          }
        }
      },
      "kind": "acp_update",
      "seq": 32,
      "at": 1785033162623
    }
  },
  {
    "runId": "019f9c44-6b72-76c3-9064-76385f83a7af",
    "seq": 33,
    "kind": "acp_update",
    "frame": {
      "notification": {
        "sessionId": "session_4f26c3f8-36ae-40fe-a881-c81e7413dc03",
        "update": {
          "sessionUpdate": "agent_thought_chunk",
          "content": {
            "type": "text",
            "text": "I'll"
          }
        }
      },
      "kind": "acp_update",
      "seq": 33,
      "at": 1785033162623
    }
  },
  {
    "runId": "019f9c44-6b72-76c3-9064-76385f83a7af",
    "seq": 34,
    "kind": "acp_update",
    "frame": {
      "notification": {
        "sessionId": "session_4f26c3f8-36ae-40fe-a881-c81e7413dc03",
        "update": {
          "sessionUpdate": "agent_thought_chunk",
          "content": {
            "type": "text",
            "text": " use"
          }
        }
      },
      "kind": "acp_update",
      "seq": 34,
      "at": 1785033162630
    }
  },
  {
    "runId": "019f9c44-6b72-76c3-9064-76385f83a7af",
    "seq": 35,
    "kind": "acp_update",
    "frame": {
      "notification": {
        "sessionId": "session_4f26c3f8-36ae-40fe-a881-c81e7413dc03",
        "update": {
          "sessionUpdate": "agent_thought_chunk",
          "content": {
            "type": "text",
            "text": " the"
          }
        }
      },
      "kind": "acp_update",
      "seq": 35,
      "at": 1785033162630
    }
  },
  {
    "runId": "019f9c44-6b72-76c3-9064-76385f83a7af",
    "seq": 36,
    "kind": "acp_update",
    "frame": {
      "notification": {
        "sessionId": "session_4f26c3f8-36ae-40fe-a881-c81e7413dc03",
        "update": {
          "sessionUpdate": "agent_thought_chunk",
          "content": {
            "type": "text",
            "text": " `"
          }
        }
      },
      "kind": "acp_update",
      "seq": 36,
      "at": 1785033162631
    }
  },
  {
    "runId": "019f9c44-6b72-76c3-9064-76385f83a7af",
    "seq": 37,
    "kind": "acp_update",
    "frame": {
      "notification": {
        "sessionId": "session_4f26c3f8-36ae-40fe-a881-c81e7413dc03",
        "update": {
          "sessionUpdate": "agent_thought_chunk",
          "content": {
            "type": "text",
            "text": "Write"
          }
        }
      },
      "kind": "acp_update",
      "seq": 37,
      "at": 1785033162631
    }
  },
  {
    "runId": "019f9c44-6b72-76c3-9064-76385f83a7af",
    "seq": 38,
    "kind": "acp_update",
    "frame": {
      "notification": {
        "sessionId": "session_4f26c3f8-36ae-40fe-a881-c81e7413dc03",
        "update": {
          "sessionUpdate": "agent_thought_chunk",
          "content": {
            "type": "text",
            "text": "`"
          }
        }
      },
      "kind": "acp_update",
      "seq": 38,
      "at": 1785033162631
    }
  },
  {
    "runId": "019f9c44-6b72-76c3-9064-76385f83a7af",
    "seq": 39,
    "kind": "acp_update",
    "frame": {
      "notification": {
        "sessionId": "session_4f26c3f8-36ae-40fe-a881-c81e7413dc03",
        "update": {
          "sessionUpdate": "agent_thought_chunk",
          "content": {
            "type": "text",
            "text": " tool"
          }
        }
      },
      "kind": "acp_update",
      "seq": 39,
      "at": 1785033162631
    }
  },
  {
    "runId": "019f9c44-6b72-76c3-9064-76385f83a7af",
    "seq": 40,
    "kind": "acp_update",
    "frame": {
      "notification": {
        "sessionId": "session_4f26c3f8-36ae-40fe-a881-c81e7413dc03",
        "update": {
          "sessionUpdate": "agent_thought_chunk",
          "content": {
            "type": "text",
            "text": " to"
          }
        }
      },
      "kind": "acp_update",
      "seq": 40,
      "at": 1785033162631
    }
  },
  {
    "runId": "019f9c44-6b72-76c3-9064-76385f83a7af",
    "seq": 41,
    "kind": "acp_update",
    "frame": {
      "notification": {
        "sessionId": "session_4f26c3f8-36ae-40fe-a881-c81e7413dc03",
        "update": {
          "sessionUpdate": "agent_thought_chunk",
          "content": {
            "type": "text",
            "text": " create"
          }
        }
      },
      "kind": "acp_update",
      "seq": 41,
      "at": 1785033162631
    }
  },
  {
    "runId": "019f9c44-6b72-76c3-9064-76385f83a7af",
    "seq": 42,
    "kind": "acp_update",
    "frame": {
      "notification": {
        "sessionId": "session_4f26c3f8-36ae-40fe-a881-c81e7413dc03",
        "update": {
          "sessionUpdate": "agent_thought_chunk",
          "content": {
            "type": "text",
            "text": " the"
          }
        }
      },
      "kind": "acp_update",
      "seq": 42,
      "at": 1785033162973
    }
  },
  {
    "runId": "019f9c44-6b72-76c3-9064-76385f83a7af",
    "seq": 43,
    "kind": "acp_update",
    "frame": {
      "notification": {
        "sessionId": "session_4f26c3f8-36ae-40fe-a881-c81e7413dc03",
        "update": {
          "sessionUpdate": "agent_thought_chunk",
          "content": {
            "type": "text",
            "text": " file"
          }
        }
      },
      "kind": "acp_update",
      "seq": 43,
      "at": 1785033162974
    }
  },
  {
    "runId": "019f9c44-6b72-76c3-9064-76385f83a7af",
    "seq": 44,
    "kind": "acp_update",
    "frame": {
      "notification": {
        "sessionId": "session_4f26c3f8-36ae-40fe-a881-c81e7413dc03",
        "update": {
          "sessionUpdate": "agent_thought_chunk",
          "content": {
            "type": "text",
            "text": " with"
          }
        }
      },
      "kind": "acp_update",
      "seq": 44,
      "at": 1785033162974
    }
  },
  {
    "runId": "019f9c44-6b72-76c3-9064-76385f83a7af",
    "seq": 45,
    "kind": "acp_update",
    "frame": {
      "notification": {
        "sessionId": "session_4f26c3f8-36ae-40fe-a881-c81e7413dc03",
        "update": {
          "sessionUpdate": "agent_thought_chunk",
          "content": {
            "type": "text",
            "text": " the"
          }
        }
      },
      "kind": "acp_update",
      "seq": 45,
      "at": 1785033162974
    }
  },
  {
    "runId": "019f9c44-6b72-76c3-9064-76385f83a7af",
    "seq": 46,
    "kind": "acp_update",
    "frame": {
      "notification": {
        "sessionId": "session_4f26c3f8-36ae-40fe-a881-c81e7413dc03",
        "update": {
          "sessionUpdate": "agent_thought_chunk",
          "content": {
            "type": "text",
            "text": " content"
          }
        }
      },
      "kind": "acp_update",
      "seq": 46,
      "at": 1785033162974
    }
  },
  {
    "runId": "019f9c44-6b72-76c3-9064-76385f83a7af",
    "seq": 47,
    "kind": "acp_update",
    "frame": {
      "notification": {
        "sessionId": "session_4f26c3f8-36ae-40fe-a881-c81e7413dc03",
        "update": {
          "sessionUpdate": "agent_thought_chunk",
          "content": {
            "type": "text",
            "text": " \""
          }
        }
      },
      "kind": "acp_update",
      "seq": 47,
      "at": 1785033162974
    }
  },
  {
    "runId": "019f9c44-6b72-76c3-9064-76385f83a7af",
    "seq": 48,
    "kind": "acp_update",
    "frame": {
      "notification": {
        "sessionId": "session_4f26c3f8-36ae-40fe-a881-c81e7413dc03",
        "update": {
          "sessionUpdate": "agent_thought_chunk",
          "content": {
            "type": "text",
            "text": "probe"
          }
        }
      },
      "kind": "acp_update",
      "seq": 48,
      "at": 1785033162974
    }
  },
  {
    "runId": "019f9c44-6b72-76c3-9064-76385f83a7af",
    "seq": 49,
    "kind": "acp_update",
    "frame": {
      "notification": {
        "sessionId": "session_4f26c3f8-36ae-40fe-a881-c81e7413dc03",
        "update": {
          "sessionUpdate": "agent_thought_chunk",
          "content": {
            "type": "text",
            "text": "\"."
          }
        }
      },
      "kind": "acp_update",
      "seq": 49,
      "at": 1785033162974
    }
  },
  {
    "runId": "019f9c44-6b72-76c3-9064-76385f83a7af",
    "seq": 50,
    "kind": "acp_update",
    "frame": {
      "notification": {
        "sessionId": "session_4f26c3f8-36ae-40fe-a881-c81e7413dc03",
        "update": {
          "sessionUpdate": "agent_thought_chunk",
          "content": {
            "type": "text",
            "text": ""
          }
        }
      },
      "kind": "acp_update",
      "seq": 50,
      "at": 1785033162974
    }
  },
  {
    "runId": "019f9c44-6b72-76c3-9064-76385f83a7af",
    "seq": 51,
    "kind": "acp_update",
    "frame": {
      "notification": {
        "sessionId": "session_4f26c3f8-36ae-40fe-a881-c81e7413dc03",
        "update": {
          "sessionUpdate": "tool_call",
          "toolCallId": "0:Write_0",
          "title": "Write",
          "kind": "edit",
          "content": [
            {
              "type": "content",
              "content": {
                "type": "text",
                "text": ""
              }
            }
          ],
          "status": "pending"
        }
      },
      "kind": "acp_update",
      "seq": 51,
      "at": 1785033162990
    }
  },
  {
    "runId": "019f9c44-6b72-76c3-9064-76385f83a7af",
    "seq": 52,
    "kind": "acp_update",
    "frame": {
      "notification": {
        "sessionId": "session_4f26c3f8-36ae-40fe-a881-c81e7413dc03",
        "update": {
          "sessionUpdate": "tool_call_update",
          "toolCallId": "0:Write_0",
          "status": "in_progress",
          "content": [
            {
              "type": "content",
              "content": {
                "type": "text",
                "text": "{\""
              }
            }
          ]
        }
      },
      "kind": "acp_update",
      "seq": 52,
      "at": 1785033163253
    }
  },
  {
    "runId": "019f9c44-6b72-76c3-9064-76385f83a7af",
    "seq": 53,
    "kind": "acp_update",
    "frame": {
      "notification": {
        "sessionId": "session_4f26c3f8-36ae-40fe-a881-c81e7413dc03",
        "update": {
          "sessionUpdate": "tool_call_update",
          "toolCallId": "0:Write_0",
          "status": "in_progress",
          "content": [
            {
              "type": "content",
              "content": {
                "type": "text",
                "text": "{\"path"
              }
            }
          ]
        }
      },
      "kind": "acp_update",
      "seq": 53,
      "at": 1785033163253
    }
  },
  {
    "runId": "019f9c44-6b72-76c3-9064-76385f83a7af",
    "seq": 54,
    "kind": "acp_update",
    "frame": {
      "notification": {
        "sessionId": "session_4f26c3f8-36ae-40fe-a881-c81e7413dc03",
        "update": {
          "sessionUpdate": "tool_call_update",
          "toolCallId": "0:Write_0",
          "status": "in_progress",
          "content": [
            {
              "type": "content",
              "content": {
                "type": "text",
                "text": "{\"path\":"
              }
            }
          ]
        }
      },
      "kind": "acp_update",
      "seq": 54,
      "at": 1785033163254
    }
  },
  {
    "runId": "019f9c44-6b72-76c3-9064-76385f83a7af",
    "seq": 55,
    "kind": "acp_update",
    "frame": {
      "notification": {
        "sessionId": "session_4f26c3f8-36ae-40fe-a881-c81e7413dc03",
        "update": {
          "sessionUpdate": "tool_call_update",
          "toolCallId": "0:Write_0",
          "status": "in_progress",
          "content": [
            {
              "type": "content",
              "content": {
                "type": "text",
                "text": "{\"path\": \""
              }
            }
          ]
        }
      },
      "kind": "acp_update",
      "seq": 55,
      "at": 1785033163254
    }
  },
  {
    "runId": "019f9c44-6b72-76c3-9064-76385f83a7af",
    "seq": 56,
    "kind": "acp_update",
    "frame": {
      "notification": {
        "sessionId": "session_4f26c3f8-36ae-40fe-a881-c81e7413dc03",
        "update": {
          "sessionUpdate": "tool_call_update",
          "toolCallId": "0:Write_0",
          "status": "in_progress",
          "content": [
            {
              "type": "content",
              "content": {
                "type": "text",
                "text": "{\"path\": \"probe"
              }
            }
          ]
        }
      },
      "kind": "acp_update",
      "seq": 56,
      "at": 1785033163254
    }
  },
  {
    "runId": "019f9c44-6b72-76c3-9064-76385f83a7af",
    "seq": 57,
    "kind": "acp_update",
    "frame": {
      "notification": {
        "sessionId": "session_4f26c3f8-36ae-40fe-a881-c81e7413dc03",
        "update": {
          "sessionUpdate": "tool_call_update",
          "toolCallId": "0:Write_0",
          "status": "in_progress",
          "content": [
            {
              "type": "content",
              "content": {
                "type": "text",
                "text": "{\"path\": \"probe.txt"
              }
            }
          ]
        }
      },
      "kind": "acp_update",
      "seq": 57,
      "at": 1785033163254
    }
  },
  {
    "runId": "019f9c44-6b72-76c3-9064-76385f83a7af",
    "seq": 58,
    "kind": "acp_update",
    "frame": {
      "notification": {
        "sessionId": "session_4f26c3f8-36ae-40fe-a881-c81e7413dc03",
        "update": {
          "sessionUpdate": "tool_call_update",
          "toolCallId": "0:Write_0",
          "status": "in_progress",
          "content": [
            {
              "type": "content",
              "content": {
                "type": "text",
                "text": "{\"path\": \"probe.txt\","
              }
            }
          ]
        }
      },
      "kind": "acp_update",
      "seq": 58,
      "at": 1785033163254
    }
  },
  {
    "runId": "019f9c44-6b72-76c3-9064-76385f83a7af",
    "seq": 59,
    "kind": "acp_update",
    "frame": {
      "notification": {
        "sessionId": "session_4f26c3f8-36ae-40fe-a881-c81e7413dc03",
        "update": {
          "sessionUpdate": "tool_call_update",
          "toolCallId": "0:Write_0",
          "status": "in_progress",
          "content": [
            {
              "type": "content",
              "content": {
                "type": "text",
                "text": "{\"path\": \"probe.txt\", \""
              }
            }
          ]
        }
      },
      "kind": "acp_update",
      "seq": 59,
      "at": 1785033163254
    }
  },
  {
    "runId": "019f9c44-6b72-76c3-9064-76385f83a7af",
    "seq": 60,
    "kind": "acp_update",
    "frame": {
      "notification": {
        "sessionId": "session_4f26c3f8-36ae-40fe-a881-c81e7413dc03",
        "update": {
          "sessionUpdate": "tool_call_update",
          "toolCallId": "0:Write_0",
          "status": "in_progress",
          "content": [
            {
              "type": "content",
              "content": {
                "type": "text",
                "text": "{\"path\": \"probe.txt\", \"content"
              }
            }
          ]
        }
      },
      "kind": "acp_update",
      "seq": 60,
      "at": 1785033163254
    }
  },
  {
    "runId": "019f9c44-6b72-76c3-9064-76385f83a7af",
    "seq": 61,
    "kind": "acp_update",
    "frame": {
      "notification": {
        "sessionId": "session_4f26c3f8-36ae-40fe-a881-c81e7413dc03",
        "update": {
          "sessionUpdate": "tool_call_update",
          "toolCallId": "0:Write_0",
          "status": "in_progress",
          "content": [
            {
              "type": "content",
              "content": {
                "type": "text",
                "text": "{\"path\": \"probe.txt\", \"content\":"
              }
            }
          ]
        }
      },
      "kind": "acp_update",
      "seq": 61,
      "at": 1785033163255
    }
  },
  {
    "runId": "019f9c44-6b72-76c3-9064-76385f83a7af",
    "seq": 62,
    "kind": "acp_update",
    "frame": {
      "notification": {
        "sessionId": "session_4f26c3f8-36ae-40fe-a881-c81e7413dc03",
        "update": {
          "sessionUpdate": "tool_call_update",
          "toolCallId": "0:Write_0",
          "status": "in_progress",
          "content": [
            {
              "type": "content",
              "content": {
                "type": "text",
                "text": "{\"path\": \"probe.txt\", \"content\": \""
              }
            }
          ]
        }
      },
      "kind": "acp_update",
      "seq": 62,
      "at": 1785033163393
    }
  },
  {
    "runId": "019f9c44-6b72-76c3-9064-76385f83a7af",
    "seq": 63,
    "kind": "acp_update",
    "frame": {
      "notification": {
        "sessionId": "session_4f26c3f8-36ae-40fe-a881-c81e7413dc03",
        "update": {
          "sessionUpdate": "tool_call_update",
          "toolCallId": "0:Write_0",
          "status": "in_progress",
          "content": [
            {
              "type": "content",
              "content": {
                "type": "text",
                "text": "{\"path\": \"probe.txt\", \"content\": \"probe"
              }
            }
          ]
        }
      },
      "kind": "acp_update",
      "seq": 63,
      "at": 1785033163393
    }
  },
  {
    "runId": "019f9c44-6b72-76c3-9064-76385f83a7af",
    "seq": 64,
    "kind": "acp_update",
    "frame": {
      "notification": {
        "sessionId": "session_4f26c3f8-36ae-40fe-a881-c81e7413dc03",
        "update": {
          "sessionUpdate": "tool_call_update",
          "toolCallId": "0:Write_0",
          "status": "in_progress",
          "content": [
            {
              "type": "content",
              "content": {
                "type": "text",
                "text": "{\"path\": \"probe.txt\", \"content\": \"probe\"}"
              }
            }
          ]
        }
      },
      "kind": "acp_update",
      "seq": 64,
      "at": 1785033163393
    }
  },
  {
    "runId": "019f9c44-6b72-76c3-9064-76385f83a7af",
    "seq": 65,
    "kind": "permission_requested",
    "frame": {
      "requestId": "019f9c44-82b0-7601-8cf3-ae7088131f66",
      "toolCallId": "0:Write_0",
      "title": "Write",
      "options": [
        {
          "optionId": "approve_once",
          "name": "Approve once",
          "kind": "allow_once"
        },
        {
          "optionId": "approve_always",
          "name": "Approve for this session",
          "kind": "allow_always"
        },
        {
          "optionId": "reject",
          "name": "Reject",
          "kind": "reject_once"
        }
      ],
      "kind": "permission_requested",
      "seq": 65,
      "at": 1785033163441
    }
  },
  {
    "runId": "019f9c44-6b72-76c3-9064-76385f83a7af",
    "seq": 66,
    "kind": "permission_resolved",
    "frame": {
      "requestId": "019f9c44-82b0-7601-8cf3-ae7088131f66",
      "optionId": "",
      "outcome": "cancelled",
      "kind": "permission_resolved",
      "seq": 66,
      "at": 1785033248492
    }
  },
  {
    "runId": "019f9c44-6b72-76c3-9064-76385f83a7af",
    "seq": 67,
    "kind": "run_finished",
    "frame": {
      "stopReason": "cancelled",
      "kind": "run_finished",
      "seq": 67,
      "at": 1785033248492
    }
  }
]
