import type { SVGProps } from 'react'

/*
 * GENERATED by refactor.mjs from apps/desktop/src-tauri/icons/icon.svg.
 *
 * Derivation, not duplication: plate, drop shadow, gradients and highlight
 * strokes are stripped and every fill is normalised to currentColor, so the
 * brand mark tracks the application icon while the icon file itself is only
 * ever opened for reading.
 */

export function AssistantMark(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      fill="none"
      role="presentation"
      viewBox="0 0 1024 1024"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <g transform="translate(-176.2745 -199.9446) scale(3.030678)">
        {' '}
        <g transform="rotate(22 145 272)">
          {' '}
          <rect fill="currentColor" height="280" rx="34" width="68" x="111" y="92" />{' '}
        </g>{' '}
        <g transform="rotate(22 246 240)">
          {' '}
          <rect fill="currentColor" height="200" rx="32" width="64" x="215" y="116" />{' '}
        </g>{' '}
        <g transform="rotate(22 332 202)">
          {' '}
          <rect fill="currentColor" height="112" rx="28" width="56" x="304" y="148" />{' '}
        </g>{' '}
      </g>
    </svg>
  )
}
