/*
 * GENERATED by refactor.mjs — do not edit by hand.
 *
 * Aliases are resolved against the export list of the installed
 * @mynaui/icons-react build, so an icon-library upgrade that renames or removes a
 * glyph fails the script instead of the runtime.
 */

export {
  ArrowUp as SubmitIcon,
  Brain as ThinkingIcon,
  ChevronDown as ChevronDownIcon,
  Dots as MoreIcon,
  File as FileIcon,
  Globe as GlobeIcon,
  Message as ThreadIcon,
  Microphone as MicIcon,
  Paperclip as AttachIcon,
  Pin as PinIcon,
  Plus as PlusIcon,
  Puzzle as ToolsIcon,
  Search as SearchIcon,
  Send as AgentIcon,
  Sparkles as ModelIcon,
  Spinner as SpinnerIcon,
  Square as StopIcon,
  X as CloseIcon,
} from '@mynaui/icons-react'
