/*
 * Generated by refactor.mjs from the component list of the installed
 * @lobehub/icons. Do not hand-edit: rerun the script instead.
 *
 * Each brand exposes an official colour variant; when a build of the package
 * omits it we fall back to the monochrome mark rather than crashing.
 */

import { DeepSeek, Zhipu, Kimi } from '@lobehub/icons'
import type { ComponentType } from 'react'

import type { AssistantModelBrand } from '../../domain/model-catalog'

export type BrandMark = ComponentType<{ readonly className?: string }>

interface BrandFamily {
  readonly Color?: BrandMark
}

const official = (family: BrandMark & BrandFamily): BrandMark => family.Color ?? family

export const MODEL_MARKS: Record<AssistantModelBrand, BrandMark> = {
  deepseek: official(DeepSeek as BrandMark & BrandFamily),
  zhipu: official(Zhipu as BrandMark & BrandFamily),
  kimi: official(Kimi as BrandMark & BrandFamily),
}
