/*
 * Generated by refactor.mjs from the files actually present in
 * assets/provider-icons. The marks are plain image assets resolved by Vite —
 * no icon package, no component library, nothing installed to draw a logo.
 *
 * Sizing is left entirely to the stylesheet, so these marks obey the same
 * token layer as every other length on the surface.
 */

import type { ComponentType } from 'react'

import deepseekMark from '../assets/provider-icons/deepseek.svg'
import zhipuMark from '../assets/provider-icons/zhipu.svg'
import kimiMark from '../assets/provider-icons/moonshot.svg'
import type { AssistantModelBrand } from '../../domain/model-catalog'

export type BrandMark = ComponentType<{ readonly className?: string }>

const providerMark = (source: string, label: string): BrandMark =>
  function ProviderMark({ className }: { readonly className?: string }) {
    return <img alt={label} className={className} draggable={false} src={source} />
  }

export const MODEL_MARKS: Record<AssistantModelBrand, BrandMark> = {
  deepseek: providerMark(deepseekMark, 'deepseek'),
  zhipu: providerMark(zhipuMark, 'zhipu'),
  kimi: providerMark(kimiMark, 'kimi'),
}
